/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:86458dc6-86fc-417a-833a-7d94e826a117",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_sauGBSnJ0",
    "aws_user_pools_web_client_id": "66hklohgd527s6a105m9ed21b5",
    "oauth": {}
};


export default awsmobile;
