/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:553551b3-addc-4219-9c60-4517f902ca58",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_hOQ0IG43z",
    "aws_user_pools_web_client_id": "6cdrgltoe8ntgukivv3i3m12gk",
    "oauth": {}
};


export default awsmobile;
